# Generated by Django 6.0.6 on 2026-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_verified',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery')], default='cod', max_length=10),
        ),
    ]
