# Generated by Django 4.2.16 on 2026-07-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_cart_id_alter_cartitem_id_alter_category_id_and_more"),
        ("shop", "0008_remove_order_payment_screenshot_and_more"),
    ]

    operations = []
